# Generated by Django 6.0.5 on 2026-05-31 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campana', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField()),
                ('esta_activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditoriaVoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante', models.CharField(max_length=255, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='elections.campana')),
            ],
        ),
        migrations.CreateModel(
            name='Plancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('candidato_principal', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='planchas_logos/')),
                ('propuesta', models.TextField()),
                ('votos_recibidos', models.IntegerField(default=0)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planchas', to='elections.campana')),
            ],
        ),
        migrations.CreateModel(
            name='Votante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_sesion', models.CharField(max_length=255, unique=True)),
                ('ya_voto', models.BooleanField(default=False)),
                ('fecha_voto', models.DateTimeField(blank=True, null=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votantes', to='elections.campana')),
            ],
        ),
    ]
