# Generated by Django 6.0.5 on 2026-05-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votante',
            name='token_sesion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='votante',
            unique_together={('token_sesion', 'campana')},
        ),
    ]
