# Generated by Django 6.0.5 on 2026-05-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_alter_votante_token_sesion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión Admin'), ('LOGOUT', 'Cierre de sesión Admin'), ('CAMPANA_CREADA', 'Campaña Creada'), ('CAMPANA_EDITADA', 'Campaña Editada'), ('VOTO_EMITIDO', 'Voto Emitido')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
